---
- hosts: localhost
  tasks:
    - name: Mount DVD read-only
      mount:
        path: /mnt/
        src: /root/ansible/opt/
        fstype: iso9660
        opts: ro
        state: present
    - name: create dirs for rhel7 and EPEL repo
      file: path={{item}} owner=apache group=apache state=directory
      with_items:
        - /var/www/html/rhel7
    - name: Extract dvd contents to directory
      command: 'tar cvf - . | (cd /var/www/html/rhel7; tar xvf -)'
    - name: Unmounting and quick clean up
      command: 'cd /; umount /mnt'
    - name: Copy GPG Key
      command: 'cp /var/www/html/rhel7/RPM-GPG-KEY-redhat-release /etc/pki/rpm-gpg/'
    - name: Creating yum repo file
      template:
        src: /root/ansible/rhel7.repo.j2
        dest: /etc/yum.repos.d/rhel7.repo
        owner: root
        group: root
        mode: '0644'
    - name: confirm apache createrepo installed
      yum: name={{item}} state=installed
      with_items:
         - httpd
         - createrepo
    - name: yum clean all & create repo
      command: 'yum clean all | createrepo /var/www/html/rhel7'
    - name: Enable rhel7 repo
      command: 'yum-config-manager --enable rhel7'

