---
# This playbook is intend for one pass execution

- name: check config locally
  hosts: localhost
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_static

- name: initializing deployment target
  hosts: all
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_dynamic

- name: zookeeper servers install dependent packages
  hosts: zookeeper_servers
  gather_facts: true
  any_errors_fatal: true
  roles:
    - packages

- name: kafka servers install dependent packages
  hosts: kafka_servers
  gather_facts: true
  any_errors_fatal: true
  roles:
    - packages

- name: deploy zookeeper
  hosts: zookeeper_servers
  any_errors_fatal: true
  roles:
    - zookeeper

- name: deploy kafka
  hosts: kafka_servers
  any_errors_fatal: true
  roles:
    - kafka
