---
- hosts: mysql_servers
  become: yes
  #gather_facts: true
  vars_files:
    - group_vars/all.yml
  pre_tasks:
   - name: Install the MySQL repo.
     yum:
       name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
       state: present
     when: ansible_os_family == "RedHat"

   - name: Override variables for MySQL (RedHat).
     set_fact:
       mysql_daemon: mysqld
       mysql_packages: ['mysql-server']
       mysql_log_error: /var/log/mysqld.err
       mysql_syslog_tag: mysqld
       mysql_pid_file: /var/run/mysqld/mysqld.pid
       mysql_socket: /var/lib/mysql/mysql.sock
     when: ansible_os_family == "RedHat"  
  roles:
    - bootstrap
    - mysql
