---
# Copyright 2016 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

# This playbook is intend for one pass execution

- name: check config locally
  hosts: localhost
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_static

- name: initializing deployment target
  hosts: all
  any_errors_fatal: true
  tags:
    - always
  roles:
    - check_config_dynamic

- hosts: kafka_servers
  serial: 1
  tasks:
    - name: stop kafka
      shell: cd {{ deploy_dir }}/scripts && ./run_kafka.sh stop

    - name: wait for kafka down
      wait_for: |
        host={{ ansible_host }} port={{ kafka_port }} state=stopped

- hosts: zookeeper_servers
  serial: 1
  tasks:
    - name: stop zookeeper
      shell: cd {{ deploy_dir }}/scripts && ./run_zookeeper.sh stop

    - name: wait for zookeeper down
      wait_for: |
        host={{ ansible_host }} port={{ zk_client_port }} state=stopped
